// ACTION TYPES

const constantDataType = {
  UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
  LOAD_INIT_LANGUAGE: 'LOAD_INIT_LANGUAGE',
  LOAD_LANGUAGE: 'LOAD_LANGUAGE',
  HOME_DATA: 'HOME_DATA',
  HOME_DATA_LOAD: 'HOME_DATA_LOAD',
  HOME_REFRESH: 'HOME_REFRESH',
  HOME_REFRESH_LOADED: 'HOME_REFRESH_LOADED',
  DETAILS_LOAD: 'DETAILS_LOAD',
  DETAILS_LOAD_SUCESS: 'DETAILS_LOAD_SUCESS',
  UP_LOAD_LANGUAGE: 'UP_LOAD_LANGUAGE',
  UP_LOAD_LANGUAGEDATA: 'UP_LOAD_LANGUAGEDATA',
  ADDVIEWAPI: 'ADDVIEWAPI',
  LESSONLIKEVIEWUPDATE: 'LESSONLIKEVIEWUPDATE',
  ADDLIKEAPI: 'ADDLIKEAPI',

  UPDATED_ALL_DATA: 'UPDATED_ALL_DATA',
  INIT_HOME_DATA_LOAD: 'INIT_HOME_DATA_LOAD',
  RETRIVEPIONTBOOSTER: 'RETRIVEPIONTBOOSTER',
  LOADCRYPTOPOINT: 'LOADCRYPTOPOINT',
  UPDATEPIONTBOOSTER: 'UPDATEPIONTBOOSTER',
};

export default constantDataType;
